### Задания по NumPy:

1. Создайте массив из списка, состоящего из чисел от 0 до 9, при помощи функции array() из модуля NumPy.

In [5]:
import numpy as np

In [10]:
np.array((0, 1, 2, 3, 4, 5, 6, 7, 8, 9))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

2. Создайте массив, состоящий из нечётных чисел от 1 до 19, при помощи функции arange() из модуля.

In [13]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

---

3. Создайте массив, состоящий из двадцати нулей.

In [15]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

---

4. Создайте двумерный массив, состоящий из двадцати единиц, в котором 5 строк и 4 столбца.

In [16]:
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

---

5. Создайте массив, состоящий из пяти равномерно распределённых чисел от 3 до 7.

In [17]:
np.linspace(3, 7, 5)

array([3., 4., 5., 6., 7.])

---

6. Создать двумерный массив, состоящий из 9 равномерно распределённых чисел от 3 до 7.

In [21]:
arr = np.linspace(3, 7, 9)

In [22]:
matrix = arr.reshape(3, 3)

In [23]:
matrix

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5],
       [6. , 6.5, 7. ]])

---

7. Создайте массив, сотстоящий из 10 случайных целых чисел из диапазона от 1 до 100. Присвойте его максимальное значение переменной max_number и выведите значение этой переменной.

In [27]:
arr = np.random.randint(1, 100, 10)

In [29]:
arr

array([74, 26, 43, 87, 25, 46, 16,  1, 44, 83], dtype=int32)

In [30]:
max_number = np.max(arr)

In [31]:
max_number

np.int32(87)

---

8. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 1 до 20. Сформируйте новый массив состоящий из 5 элементов первого массива, начания со 2-го по порядку. Выведите значения обоих массивов.

In [32]:
array = np.random.randint(1, 20, 10)

In [33]:
array

array([ 3,  9,  4,  4,  4,  1, 18,  5, 18,  8], dtype=int32)

In [34]:
new_array = array[1:6]

In [35]:
new_array

array([9, 4, 4, 4, 1], dtype=int32)

---

9. Создайте двумерный массив, состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца. Сформируйте новый массив, состоящий из элементов второй и третьей строки, первого и второго столбца по порядку. Выведите значения обоих массивов при помощи функции print().

In [38]:
array = np.random.randint(3, 11, 12)
twoDarray = array.
print(array)

[ 6  6  6  7  7  3 10  7  8  7 10  6]
