1. Импортируйте пакет `numpy` под именем `np`.

In [62]:
import numpy as np

2. Распечатайте версию `numpy`.

In [63]:
print(np.__version__)

2.1.3


3. Создайте вектор со значениями от 10 до 49.

In [64]:
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Переверните вектор (первый элемент становится последним).

In [65]:
np.arange(10, 50, 1)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

5. Создайте массив 5x5 со случайными значениями, найдите среднее значение и медиану для каждой строки.

In [66]:
matrix = np.random.random((5, 5))
print(matrix)

[[0.92268407 0.47205381 0.74052798 0.17383571 0.30271178]
 [0.76130979 0.43516435 0.74187847 0.01305949 0.32620078]
 [0.7871067  0.7305967  0.53312529 0.45280836 0.31042718]
 [0.33752563 0.47284644 0.80312014 0.26934942 0.352839  ]
 [0.38689553 0.27758245 0.99235425 0.1182048  0.84723918]]


In [67]:
average = np.mean(matrix, axis=1)
print(average)

[0.52236267 0.45552258 0.56281284 0.44713613 0.52445524]


In [68]:
average_in_line = np.median(matrix, axis=1)
print(average_in_line)

[0.47205381 0.43516435 0.53312529 0.352839   0.38689553]


6. Преобразуйте одномерный массив из 27 элементов целого типа в трёхмерный (3x3x3)

In [69]:
matrix = np.arange(27)
print(matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [70]:
matrix_3x3x3 = matrix.reshape((3, 3, 3))
print(matrix_3x3x3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива `numpy` из типа данных float в integer.

In [71]:
array = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

In [72]:
converted = array.astype(int)
print(converted)

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив `numpy` в логический массив `numpy`.

In [73]:
array = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 1]])

In [74]:
converted = array.astype(bool)
print(converted)

[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива `numpy` горизонтально (hstack), т. е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах).

In [75]:
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2 = np.array([[7, 8, 9], [10, 11, 12]])
result = np.hstack((array_1, array_2))
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива `numpy` вертикально (vstack), т. е. 2 массива, имеющих одинаковое последнее измерение (количество столбцов в 2D-массиве).

In [76]:
array_1 = np.array([[1, 2], [3, 4], [5, 6]])
array_2 = np.array([[7, 8], [9, 10], [10, 11]])
result = np.vstack((array_1, array_2))
print(result)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов `numpy` извлеките индексы, в которых совпадают элементы (np.where).

In [77]:
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([1, 3, 2, 4, 5])
result = np.where(array_1 == array_2)
print(result)

(array([0, 3, 4]),)


12. Выведите результат умножения 2 матриц (в виде массива `numpy`).

In [78]:
array_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2 = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
result = array_1 @ array_2
print(result)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу.

In [79]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


14. Вычислите синус массива углов (в радианах) с помощью `numpy`.

In [80]:
angles = np.array([3.14, 3.14 / 2, 6.28])
result = np.sin(angles)
print(result)

[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортируйте вектор.

In [81]:
vector = np.random.random(size=[10])
print(vector)

[0.63801081 0.1246218  0.50104884 0.23284726 0.25496369 0.58653082
 0.40691932 0.9766344  0.13830682 0.31452587]


In [82]:
result = np.sort(vector)
print(result)

[0.1246218  0.13830682 0.23284726 0.25496369 0.31452587 0.40691932
 0.50104884 0.58653082 0.63801081 0.9766344 ]


16. Проверьте, одинаковы ли два `numpy` массива.

In [83]:
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([1, 2, 3, 4, 5])
result = np.array_equal(array_1, array_2)
print(result)

True


17. В одномерном массиве заменить максимальный элемент на ноль.

In [84]:
array = np.random.random(10)
print(array)

[0.31061947 0.99284292 0.56685862 0.22940227 0.38852893 0.8767107
 0.26781533 0.01091802 0.85267027 0.6769565 ]


In [86]:
max_value = array.argmax()
array[max_value] = 0
print(array)

[0.31061947 0.         0.56685862 0.22940227 0.38852893 0.8767107
 0.26781533 0.01091802 0.85267027 0.6769565 ]


18. Замените все нечётные числа одномерного массива на -1.

In [92]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for index, element in enumerate(array):
    if element % 2 != 0:
        array[index] = -1
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. Замените все элементы в массиве `numpy` больше 30 или меньше 5 новым значением 10.

In [93]:
array = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])
for index, element in enumerate(array):
    if element > 30 or element < 5:
        array[index] = 10
print(array)

[10 10 20 10 10  5  6 10  8 10]


20. Отсортируйте двумерный массив по столбцам.

In [95]:
array = np.array([[11, 5, 3], [4, 15, 6], [7, 8, 19]])
result = np.sort(array, axis=0)
print(result)

[[ 4  5  3]
 [ 7  8  6]
 [11 15 19]]
